"""
Phase 2: Classification

Identify modification type from 28 MOFSL types

Auto-generated by MAFIA. This is a CAMS-compatible LangGraph node.
Drop into src/agent/nodes/ and wire into mafia_graph.py.
"""
from __future__ import annotations
import logging
from typing import Any
from langchain_core.messages import SystemMessage
from workflow.states import WorkflowState
from workflow.engine import WorkflowEngine

logger = logging.getLogger(__name__)

PHASE_STATE = WorkflowState.CLASSIFICATION
PHASE_LABEL = "Classification"
PHASE_DESCRIPTION = "Identify modification type from 28 MOFSL types"

# Tools this phase focuses on.
# Other tools remain available — LLM uses these preferentially.
PHASE_TOOLS = ["classify_modification_type", "validate_client_eligibility", "determine_channel", "get_document_checklist", "get_client_profile"]


class ClassificationNode:
    """
    Phase 2: Classification

    Identify modification type from 28 MOFSL types
    Transitions workflow state to CLASSIFICATION on entry.
    On completion, next phase is ELIGIBILITY_CHECK.
    """

    def __init__(self, llm: Any, tools: list, config: dict):
        self.llm = llm
        self.config = config
        self.engine = WorkflowEngine()
        # Prefer phase-specific tools; fall back to all tools
        phase_tools = [
            t for t in tools
            if hasattr(t, "name") and t.name in PHASE_TOOLS
        ]
        self.tools = phase_tools if phase_tools else tools
        self.llm_with_tools = llm.bind_tools(self.tools) if self.tools else llm

    def __call__(self, state: dict) -> dict:
        """Execute Classification phase."""
        messages = state.get("messages", [])
        request_id = state.get("request_id", "unknown")
        current_phase = state.get("current_phase", "INITIATED")

        # Transition business state to this phase
        try:
            current = WorkflowState(current_phase)
            self.engine.transition(
                current=current,
                target=PHASE_STATE,
                request_id=request_id,
                reason=f"Entering Classification phase"
            )
        except Exception as e:
            logger.warning(f"State transition skipped: {e}")

        # Inject phase context so LLM knows what to focus on
        phase_context = SystemMessage(content=(
            f"[WORKFLOW PHASE: Classification] "
            f"Identify modification type from 28 MOFSL types. "
            f"Complete all required steps for this phase using available tools. "
            f"Indicate when this phase is complete and ready to proceed."
        ))

        response = self.llm_with_tools.invoke([phase_context] + messages)

        return {
            **state,
            "messages": messages + [response],
            "current_phase": PHASE_STATE.value,
        }