"""
Workflow Engine — validates state transitions and logs audit trail.
Auto-generated by MAFIA. Same pattern for every agent.

Usage:
    engine = WorkflowEngine()
    new_state = engine.transition(
        current=WorkflowState.INITIATED,
        target=WorkflowState.DATA_COLLECTION,
        request_id="REQ-001",
        reason="Customer submitted application"
    )
"""
from __future__ import annotations
import logging
from datetime import datetime, timezone
from workflow.states import WorkflowState, VALID_TRANSITIONS, can_transition, PHASE_LABELS

logger = logging.getLogger(__name__)


class InvalidTransitionError(Exception):
    """Raised when a state transition is not permitted."""
    pass


class WorkflowEngine:
    """
    Validates and executes workflow state transitions.

    Two guarantees:
    1. No invalid transitions — raises InvalidTransitionError if not allowed
    2. Full audit trail — every transition logged with timestamp + reason
    """

    def transition(
        self,
        current: WorkflowState,
        target: WorkflowState,
        request_id: str = "unknown",
        reason: str = "",
    ) -> WorkflowState:
        """
        Attempt a state transition.

        Args:
            current:    Current workflow state
            target:     Desired new state
            request_id: Customer request/application ID for audit trail
            reason:     Why this transition is happening

        Returns:
            The new WorkflowState (same as target if successful)

        Raises:
            InvalidTransitionError: if the transition is not permitted
        """
        if not can_transition(current, target):
            allowed = [s.value for s in VALID_TRANSITIONS.get(current, set())]
            raise InvalidTransitionError(
                f"[{request_id}] Cannot transition {current.value} → {target.value}. "
                f"Allowed: {allowed}"
            )

        timestamp = datetime.now(timezone.utc).isoformat()
        current_label = PHASE_LABELS.get(current, current.value)
        target_label = PHASE_LABELS.get(target, target.value)

        logger.info(
            f"[{timestamp}] [{request_id}] WORKFLOW: "
            f"{current_label} → {target_label}"
            + (f" | Reason: {reason}" if reason else "")
        )

        return target

    def get_valid_next_states(self, current: WorkflowState) -> list[WorkflowState]:
        """Return all states this state can legally transition to."""
        return list(VALID_TRANSITIONS.get(current, set()))

    def get_label(self, state: WorkflowState) -> str:
        """Human-readable label for a state."""
        return PHASE_LABELS.get(state, state.value)
