"""
Business state machine for MA01 Modification Request Classifier.
Generated by MAFIA — do not edit manually.

Tracks where each customer request is in the workflow across sessions.
Separate from LangGraph execution state (which only lives during one conversation).
SOP-derived transitions enforce compliance: no state can be skipped.
"""
from __future__ import annotations
from enum import Enum


class WorkflowState(str, Enum):
    INITIATED = "INITIATED"
    REQUEST_INTAKE = "REQUEST_INTAKE"
    CLASSIFICATION = "CLASSIFICATION"
    ELIGIBILITY_CHECK = "ELIGIBILITY_CHECK"
    CHANNEL_ROUTING = "CHANNEL_ROUTING"
    DOCUMENT_CHECKLIST = "DOCUMENT_CHECKLIST"
    COMPLETED = "COMPLETED"
    OBJECTED = "OBJECTED"
    REJECTED = "REJECTED"
    CANCELLED = "CANCELLED"


# ---------------------------------------------------------------------------
# Allowed transitions: source state → set of valid destination states
# Every transition must be approved here before the engine will allow it.
# ---------------------------------------------------------------------------
VALID_TRANSITIONS: dict[WorkflowState, set[WorkflowState]] = {
    WorkflowState.INITIATED: {WorkflowState.REQUEST_INTAKE, WorkflowState.REJECTED, WorkflowState.CANCELLED},
    WorkflowState.REQUEST_INTAKE: {WorkflowState.CLASSIFICATION, WorkflowState.OBJECTED, WorkflowState.REJECTED, WorkflowState.CANCELLED},
    WorkflowState.CLASSIFICATION: {WorkflowState.ELIGIBILITY_CHECK, WorkflowState.OBJECTED, WorkflowState.REJECTED, WorkflowState.CANCELLED},
    WorkflowState.ELIGIBILITY_CHECK: {WorkflowState.CHANNEL_ROUTING, WorkflowState.OBJECTED, WorkflowState.REJECTED, WorkflowState.CANCELLED},
    WorkflowState.CHANNEL_ROUTING: {WorkflowState.DOCUMENT_CHECKLIST, WorkflowState.OBJECTED, WorkflowState.REJECTED, WorkflowState.CANCELLED},
    WorkflowState.DOCUMENT_CHECKLIST: {WorkflowState.COMPLETED, WorkflowState.REJECTED},
    WorkflowState.OBJECTED: {WorkflowState.REQUEST_INTAKE, WorkflowState.CANCELLED},
    WorkflowState.REJECTED: set(),
    WorkflowState.CANCELLED: set(),
    WorkflowState.COMPLETED: set(),
}


PHASE_LABELS: dict[WorkflowState, str] = {
    WorkflowState.INITIATED: "Initiated",
    WorkflowState.REQUEST_INTAKE: "Request Intake",
    WorkflowState.CLASSIFICATION: "Classification",
    WorkflowState.ELIGIBILITY_CHECK: "Eligibility Check",
    WorkflowState.CHANNEL_ROUTING: "Channel Routing",
    WorkflowState.DOCUMENT_CHECKLIST: "Document Checklist",
    WorkflowState.COMPLETED: "Completed",
    WorkflowState.OBJECTED: "Objected — additional info required",
    WorkflowState.REJECTED: "Rejected",
    WorkflowState.CANCELLED: "Cancelled",
}


def is_terminal(state: WorkflowState) -> bool:
    """Returns True if no further transitions are possible."""
    return not VALID_TRANSITIONS.get(state)


def can_transition(from_state: WorkflowState, to_state: WorkflowState) -> bool:
    """Check if a transition is valid before attempting it."""
    return to_state in VALID_TRANSITIONS.get(from_state, set())