"""
Tool: classify_modification_type
Description: Identifies which of the 28 MOFSL modification types the customer is requesting from their free-text input
API: Internal NLP rules engine
Auto-generated by MAFIA. Fill in the real API call below.
CAMS auto-discovers this via the @tool decorator on startup.
"""
import os
import json
import httpx
from langchain_core.tools import tool

MOCK_MODE = os.getenv("MOCK_MODE", "true").lower() == "true"


@tool
def classify_modification_type(client_input: str, client_code: str) -> str:
    """Identifies which of the 28 MOFSL modification types the customer is requesting from their free-text input"""
    if MOCK_MODE:
        return '{"modification_type": "mobile_update", "confidence": 0.97, "channel": "emod", "ambiguous": false, "display_name": "Mobile Number Update"}'

    # TODO: Replace with real Internal NLP rules engine call
    url = os.getenv("CLASSIFY_MODIFICATION_TYPE_URL", "")
    api_key = os.getenv("CLASSIFY_MODIFICATION_TYPE_API_KEY", "")

    if not url:
        return json.dumps({"success": False, "error": "CLASSIFY_MODIFICATION_TYPE_URL not configured"})

    try:
        with httpx.Client(timeout=30.0) as client:
            response = client.post(
                url,
                json={"client_input": client_input, "client_code": client_code},
                headers={"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"}
            )
            response.raise_for_status()
            return json.dumps(response.json())
    except Exception as e:
        return json.dumps({"success": False, "error": str(e), "tool": "classify_modification_type"})
