"""
Tool: determine_channel
Description: Maps modification type to correct processing channel (Emod/CBOS/SRA+JIRA) and returns processing SLA
API: Internal routing rules engine
Auto-generated by MAFIA. Fill in the real API call below.
CAMS auto-discovers this via the @tool decorator on startup.
"""
import os
import json
import httpx
from langchain_core.tools import tool

MOCK_MODE = os.getenv("MOCK_MODE", "true").lower() == "true"


@tool
def determine_channel(modification_type: str) -> str:
    """Maps modification type to correct processing channel (Emod/CBOS/SRA+JIRA) and returns processing SLA"""
    if MOCK_MODE:
        return '{"channel": "emod", "channel_name": "Emod Online Portal", "sla_days": 2, "process_url": "https://emod.mofsl.com/modifications"}'

    # TODO: Replace with real Internal routing rules engine call
    url = os.getenv("DETERMINE_CHANNEL_URL", "")
    api_key = os.getenv("DETERMINE_CHANNEL_API_KEY", "")

    if not url:
        return json.dumps({"success": False, "error": "DETERMINE_CHANNEL_URL not configured"})

    try:
        with httpx.Client(timeout=30.0) as client:
            response = client.post(
                url,
                json={"modification_type": modification_type},
                headers={"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"}
            )
            response.raise_for_status()
            return json.dumps(response.json())
    except Exception as e:
        return json.dumps({"success": False, "error": str(e), "tool": "determine_channel"})
