"""
Tool: get_client_profile
Description: Fetches basic client details from CBOS — name, segment, account type, registered contacts
API: CBOS Client Master API
Auto-generated by MAFIA. Fill in the real API call below.
CAMS auto-discovers this via the @tool decorator on startup.
"""
import os
import json
import httpx
from langchain_core.tools import tool

MOCK_MODE = os.getenv("MOCK_MODE", "true").lower() == "true"


@tool
def get_client_profile(client_code: str) -> str:
    """Fetches basic client details from CBOS — name, segment, account type, registered contacts"""
    if MOCK_MODE:
        return '{"client_name": "Rajesh Kumar", "segment": "individual", "account_type": "both", "registered_mobile": "XXXXXX7890", "registered_email": "r****@gmail.com"}'

    # TODO: Replace with real CBOS Client Master API call
    url = os.getenv("GET_CLIENT_PROFILE_URL", "")
    api_key = os.getenv("GET_CLIENT_PROFILE_API_KEY", "")

    if not url:
        return json.dumps({"success": False, "error": "GET_CLIENT_PROFILE_URL not configured"})

    try:
        with httpx.Client(timeout=30.0) as client:
            response = client.post(
                url,
                json={"client_code": client_code},
                headers={"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"}
            )
            response.raise_for_status()
            return json.dumps(response.json())
    except Exception as e:
        return json.dumps({"success": False, "error": str(e), "tool": "get_client_profile"})
