"""
Tool: get_document_checklist
Description: Returns the complete list of required documents for a modification type per SEBI KYC guidelines
API: Internal document rules engine
Auto-generated by MAFIA. Fill in the real API call below.
CAMS auto-discovers this via the @tool decorator on startup.
"""
import os
import json
import httpx
from langchain_core.tools import tool

MOCK_MODE = os.getenv("MOCK_MODE", "true").lower() == "true"


@tool
def get_document_checklist(modification_type: str, client_segment: str) -> str:
    """Returns the complete list of required documents for a modification type per SEBI KYC guidelines"""
    if MOCK_MODE:
        return '{"mandatory_docs": ["OTP verification on old mobile", "OTP verification on new mobile", "Government ID proof"], "optional_docs": ["Aadhaar (masked)", "Passport"], "special_notes": "Both old and new numbers must be active for OTP delivery"}'

    # TODO: Replace with real Internal document rules engine call
    url = os.getenv("GET_DOCUMENT_CHECKLIST_URL", "")
    api_key = os.getenv("GET_DOCUMENT_CHECKLIST_API_KEY", "")

    if not url:
        return json.dumps({"success": False, "error": "GET_DOCUMENT_CHECKLIST_URL not configured"})

    try:
        with httpx.Client(timeout=30.0) as client:
            response = client.post(
                url,
                json={"modification_type": modification_type, "client_segment": client_segment},
                headers={"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"}
            )
            response.raise_for_status()
            return json.dumps(response.json())
    except Exception as e:
        return json.dumps({"success": False, "error": str(e), "tool": "get_document_checklist"})
