"""
Tool: validate_client_eligibility
Description: Checks CBOS account status, pending SRA tickets, freeze status before accepting any modification request
API: CBOS Account Status API
Auto-generated by MAFIA. Fill in the real API call below.
CAMS auto-discovers this via the @tool decorator on startup.
"""
import os
import json
import httpx
from langchain_core.tools import tool

MOCK_MODE = os.getenv("MOCK_MODE", "true").lower() == "true"


@tool
def validate_client_eligibility(client_code: str) -> str:
    """Checks CBOS account status, pending SRA tickets, freeze status before accepting any modification request"""
    if MOCK_MODE:
        return '{"eligible": true, "account_status": "active", "block_reason": "", "pending_sra": false}'

    # TODO: Replace with real CBOS Account Status API call
    url = os.getenv("VALIDATE_CLIENT_ELIGIBILITY_URL", "")
    api_key = os.getenv("VALIDATE_CLIENT_ELIGIBILITY_API_KEY", "")

    if not url:
        return json.dumps({"success": False, "error": "VALIDATE_CLIENT_ELIGIBILITY_URL not configured"})

    try:
        with httpx.Client(timeout=30.0) as client:
            response = client.post(
                url,
                json={"client_code": client_code},
                headers={"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"}
            )
            response.raise_for_status()
            return json.dumps(response.json())
    except Exception as e:
        return json.dumps({"success": False, "error": str(e), "tool": "validate_client_eligibility"})
